name: Build and deploy Node.js app to Azure Web App - gabai

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm packages - backend
        run: |
          cd backend
          npm install
          
      - name: Install npm packages - frontend
        run: |
          cd frontend
          npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: backend
          
      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80BC114EBDCA48AEBD8C792A16D51C7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C7DAB043FBA94F749F5B4846D66D8D68 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C1E09881B4834D93B9F5726E230146DC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gabai'
          slot-name: 'Production'
          package: .
